### ISSUE TITLE
Reframing the goal of this starter

### ISSUE THREAD

**Issue by bclozel** [jliu666/docker-api-spring-boot#1]
"docker-java" seems rather general, and the current README doesn't make the goal of this starter really clear.

Is this starter only about configuring a docker java client? In this case, renaming this starter to docker-client-spring-boot-starter could be a better fit.

Currently the starter only provides a single configuration property namespace and uses the client builder to create a couple of beans. Are there other opinions or features that this starter could offer to developers?

**Comment by jliuold** [comment]
I renamed the project name to docker-api. Because both docker-java and docker-client are wrappers of the docker api.

**Comment by bclozel** [comment]
The new name looks fine!

In a [previous comment](https://github.com/jliu666/docker-api-spring-boot/issues/3#issuecomment-376652388) I said this starter should come with at least one compile dependency. Reading the README of this project, I don't see the difference between docker-java and docker-client.

I'm not really familiar with this library, so feel free to close this issue if you think this is the right choice here.

**Comment by jliuold** [comment]
OK!
Both docker-java and docker-client really have many differences. I will add more about docker-java and docker-client so that users can chose the right choose for their projects.

**Comment by bclozel** [comment]
Works for me.
Thanks!
