### ISSUE TITLE
Review conditions on auto-configuration

### ISSUE THREAD

**Issue by bclozel** [jliu666/docker-api-spring-boot#2]
The current auto-configuration has `@ConditionalOnClass(DockerClientProperties.class)`.

Since this properties class is part of the same package, this condition always return true. Did you mean to do that on a library class like `DockerClientBuilder` ?

**Comment by jliuold** [comment]
I have improved it now. Could you give me more suggestions?

**Comment by bclozel** [comment]
Conditions look good now - I see that you're working against two different `DockerClient` APIs - separating the configurations was a good choice here.

Thanks!
