### ISSUE TITLE
Review dependency management

### ISSUE THREAD

**Issue by bclozel** [jliu666/docker-api-spring-boot#3]
Given the layout of this starter (you've separated the auto-configuration and the actual starter), the autoconfigure module should not have a compile dependency on `docker-java`, it should be optional.

Only the starter should bring that dependency.

**Comment by jliuold** [comment]
The project dependencies have been improved. Now both docker-java and docker-client are optional. User can chose one item.

**Comment by bclozel** [comment]
There's been a misunderstanding.
It seems that you've now merged your auto-configuration and your starter into a single project - given the size of the auto-configuration, I don't think it's a bad idea.

Now your starter should absolutely come with compile dependencies; adding your starter to a Spring Boot application, without any other action from the developer, should do something.

Note: `spring-boot-configuration-processor` should be marked as optional, as it's only useful when you build your project (to generate the configuration metadata). But projects depending on this starter don't need this dependency.

**Comment by jliuold** [comment]
Hi!
Should Both docker-java and docker-client's dependencies are optional? If both are optional, the starter does nothing after adding the starter dependency without adding other dependency.

**Comment by bclozel** [comment]
I've read the README file in your repository. At that point I think it's up to you.
If you think your starter should have a default opinion, then mark one of the dependencies as compile but then document how to switch to the other one. If you think it's really the developer's choice and your starter does not favor one over the other, then marking both as optional (but still providing dependency management for them!) is fine.

**Comment by jliuold** [comment]
Thank you!
The `spring-boot-configuration-processor` has been marked as optional now.

**Comment by bclozel** [comment]
Thanks!
